### ISSUE TITLE
remove unittest2 dependency 

### ISSUE THREAD

**Issue by hpk42** [Pylons/pyramid_chameleon#17]
I was just trying to install pyramid_chameleon on an old system (which i can't easily get upgraded) and the install fails when trying to install unittest2 -- which makes me wonder why unittest2 is a dependency of the pyramid_chameleon package?  note that you can easily add "unittest2" to tox.ini if it's about running tests.

**Comment by mmerickel** [comment]
@hpk42 I can't find a unittest2 reference in this repo.
