### ISSUE TITLE
Bring repo up to standards and release

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid_chameleon#22]
- [x] Update `conf.py` (@stevepiercy)
- [x] Update `contributing.md` (@stevepiercy)
- [x] Add `RELEASING.txt` (@stevepiercy)
- [x] Update `README.rst` (@stevepiercy)
- [x] `setup.py`: bump Sphinx version, update trove classifiers
- [x] `tox.ini`: drop 3.3, add 3.5, 3.6, 3.7 nightly as allowed failure, use matrix(?)
- [x] `travis.yml`: drop 3.3, add 3.5, 3.6, 3.7 nightly as allowed failure
- [x] get [complete test coverage on #20](https://travis-ci.org/Pylons/pyramid_chameleon/jobs/386169168#L554)
- [ ] other?

**Comment by stevepiercy** [comment]
Anyone else want RTD admin access? https://readthedocs.org/projects/pyramid-chameleon/

**Comment by stevepiercy** [comment]
I've done all my things here.

For the other three items, are the proposed versions what we want?

Are there any other items that we might have missed?

**Comment by tseaver** [comment]
Coverage is at 100%.
