### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by gforcada** [Pylons/pyramid_chameleon#27]
Last release on pypi dates from 2014 (6 years ago!) and there has been a fair amount of changes: https://github.com/Pylons/pyramid_chameleon/compare/0.3...master

So, it might be a good time to cut a new release? :thinking:

**Comment by stevepiercy** [comment]
ping pypi maintainers @mcdonc @mmerickel @bertjwregeer

**Comment by silenius** [comment]
ping

**Comment by mcdonc** [comment]
@silenus apologies for the absurd delay but a release will be happening pretty soon (within the next week or so), after I am able to merge some variant of https://github.com/Pylons/pyramid_chameleon/pull/31
